### ISSUE TITLE
How to generate palantir_lineage_cells

### ISSUE THREAD

**Issue by jldeng3** [settylab/Mellon#11]
How to generate data for palantir_lineage_cells using own data

**Comment by katosh** [comment]
Hello @jldeng3,

Thank you for your inquiry. I am guesing you are referring to the cell-selection for a specific differentiation branch used in the [tutorial for comparison of density along pseudotime](https://mellon.readthedocs.io/en/latest/notebooks/basic_tutorial.html#Comparison-of-density-along-pseudotime).

![](https://mellon.readthedocs.io/en/latest/_images/notebooks_basic_tutorial_21_0.png)

You can use any method to identify cells of a specific branch making a boolean mask. Here are two suggestions:

 1. Using an existing cell-type annotation
```Python
import pandas as pd

ad.obsm["lineage_cells"] = pd.DataFrame({
    "branch_1": ad.obs["celltype"].isin(celltypes_of_branch_1),
    "branch_2": ad.obs["celltype"].isin(celltypes_of_branch_2),
})
```

 2. Using `palantir.presults.select_branch_cells` based on cell-fate probabilities, as outlined in the [Palantir tutorial](https://palantir.readthedocs.io/en/latest/notebooks/Palantir_sample_notebook.html#Gene-expression-trends).

Please let me know if this resolves the issue or if you have any further questions.

**Comment by jldeng3** [comment]
Thank you very much,it is good,solvels the problem.



---- Replied Message ----
| From | Dominik J. ***@***.***> |
| Date | 07/18/2024 01:42 |
| To | ***@***.***> |
| Cc | Jianlong ***@***.***>***@***.***> |
| Subject | Re: [settylab/Mellon] How to generate palantir_lineage_cells (Issue #11) |

Hello @jldeng3,

Thank you for your inquiry. I am guesing you are referring to the cell-selection for a specific differentiation branch used in the tutorial for comparison of density along pseudotime.

You can use any method to identify cells of a specific branch making a boolean mask. Here are two suggestions:

Using an existing cell-type annotation
importpandasaspdad.obsm["lineage_cells"] =pd.DataFrame({
    "branch_1": ad.obs["celltype"].isin(celltypes_of_branch_1),
    "branch_2": ad.obs["celltype"].isin(celltypes_of_branch_2),
})
Using palantir.presults.select_branch_cells based on cell-fate probabilities, as outlined in the Palantir tutorial.

Please let me know if this resolves the issue or if you have any further questions.
