### ISSUE TITLE
Mellon  article

### ISSUE THREAD

**Issue by yitengfei120011** [settylab/Mellon#8]
HI, I found that this article has just been published. I want to read it carefully. Can you send me the article? 

![image](https://github.com/settylab/Mellon/assets/128008224/e2d9d794-f1f2-4fb5-8554-2da36aa8f3f3)

**Comment by ManuSetty** [comment]
Can you please send an email to the address listed in the manuscript: https://www.nature.com/articles/s41592-024-02302-w#author-information
